/* Generated by Nimrod Compiler v0.9.6 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/nfs/users/jfilstrup/code/nim/Nimrod/lib -o /nfs/users/jfilstrup/code/nim/nim-monad/src/nimcache/maybe.o /nfs/users/jfilstrup/code/nim/nim-monad/src/nimcache/maybe.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct maybe90014 maybe90014;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
struct  maybe90014  {
NIM_BOOL Valid;
union {
NI Value;
} validU;
};
typedef struct {
N_NIMCALL_PTR(maybe90014, ClPrc) (NI x_90092, void* ClEnv);
void* ClEnv;
} TY90098;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CLOSURE_PTR(maybe90014, TMP139) (NI x_90092);
N_NIMCALL(NIM_BOOL, HEX3F_90105)(maybe90014 m_90111);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_17801)(void);
static N_INLINE(void, popFrame)(void);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
STRING_LITERAL(TMP138, "value", 5);
STRING_LITERAL(TMP143, "Just ", 5);
STRING_LITERAL(TMP144, "Nothing", 7);
extern TFrame* frameptr_15242;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_15242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_15242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_15242;
	frameptr_15242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_17801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_15242 = (*frameptr_15242).prev;
}

N_NIMCALL(NIM_BOOL, HEX3F_90105)(maybe90014 m_90111) {
	NIM_BOOL result;
	nimfr("?", "maybe.nim")
	result = 0;
	nimln(10, "maybe.nim");
	nimln(10, "maybe.nim");
	result = m_90111.Valid;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(maybe90014, HEX3EHEX3EHEX3D_90079)(maybe90014 m_90086, TY90098 p_90097) {
	maybe90014 result;
	nimfr(">>=", "maybe.nim")
	memset((void*)&result, 0, sizeof(result));
	nimln(29, "maybe.nim");
	{
		NIM_BOOL LOC3;
		nimln(29, "maybe.nim");
		LOC3 = 0;
		LOC3 = HEX3F_90105(m_90086);
		if (!LOC3) goto LA4;
		nimln(30, "maybe.nim");
		nimln(30, "maybe.nim");
		if (!(((2 &(1<<((m_90086.Valid)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP138));
		result = p_90097.ClEnv? p_90097.ClPrc(m_90086.validU.Value, p_90097.ClEnv):((TMP139)(p_90097.ClPrc))(m_90086.validU.Value);
		goto BeforeRet;
	}
	goto LA1;
	LA4: ;
	{
		maybe90014 LOC7;
		nimln(32, "maybe.nim");
		nimln(32, "maybe.nim");
		memset((void*)&LOC7, 0, sizeof(LOC7));
		LOC7.Valid = NIM_FALSE;
		result = LOC7;
		goto BeforeRet;
	}
	LA1: ;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, HEX24_90210)(maybe90014 m_90216) {
	NimStringDesc* result;
	nimfr("$", "maybe.nim")
	result = 0;
	nimln(13, "maybe.nim");
	{
		NIM_BOOL LOC3;
		NimStringDesc* LOC6;
		NimStringDesc* LOC7;
		nimln(13, "maybe.nim");
		LOC3 = 0;
		LOC3 = HEX3F_90105(m_90216);
		if (!LOC3) goto LA4;
		nimln(14, "maybe.nim");
		nimln(14, "maybe.nim");
		nimln(14, "maybe.nim");
		LOC6 = 0;
		nimln(14, "maybe.nim");
		if (!(((2 &(1<<((m_90216.Valid)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP138));
		LOC7 = 0;
		LOC7 = nimIntToStr(m_90216.validU.Value);
		LOC6 = rawNewString(LOC7->Sup.len + 5);
appendString(LOC6, ((NimStringDesc*) &TMP143));
appendString(LOC6, LOC7);
		result = LOC6;
		goto BeforeRet;
	}
	goto LA1;
	LA4: ;
	{
		nimln(16, "maybe.nim");
		nimln(16, "maybe.nim");
		result = copyString(((NimStringDesc*) &TMP144));
		goto BeforeRet;
	}
	LA1: ;
	BeforeRet: ;
	popFrame();
	return result;
}
N_NOINLINE(void, HEX00_maybeInit)(void) {
	nimfr("maybe", "maybe.nim")
	popFrame();
}

N_NOINLINE(void, HEX00_maybeDatInit)(void) {
}

