/* Generated by Nimrod Compiler v0.9.6 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/nfs/users/jfilstrup/code/nim/Nimrod/lib -o /nfs/users/jfilstrup/code/nim/nim-monad/src/nimcache/testing.o /nfs/users/jfilstrup/code/nim/nim-monad/src/nimcache/testing.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <stdio.h>
typedef struct maybe90014 maybe90014;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
struct  maybe90014  {
NIM_BOOL Valid;
union {
NI Value;
} validU;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef struct {
N_NIMCALL_PTR(maybe90014, ClPrc) (NI x_90092, void* ClEnv);
void* ClEnv;
} TY90098;
typedef N_CLOSURE_PTR(maybe90014, TMP140) (NI x_90077, void* ClEnv);
typedef N_CLOSURE_PTR(maybe90014, TMP141) (NI x_90144, void* ClEnv);
typedef N_CLOSURE_PTR(maybe90014, TMP142) (NI x_90175, void* ClEnv);
N_NIMCALL(maybe90014, adder_90007)(NI x);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_17801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(maybe90014, HEX3EHEX3EHEX3D_90079)(maybe90014 m_90086, TY90098 p_90097);
N_NIMCALL(NIM_BOOL, HEX3F_90105)(maybe90014 m_90111);
N_NIMCALL(NimStringDesc*, HEX24_90210)(maybe90014 m_90216);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
N_NOINLINE(void, systemInit)(void);
N_NOINLINE(void, systemDatInit)(void);
N_NOINLINE(void, HEX00_monadInit)(void);
N_NOINLINE(void, HEX00_monadDatInit)(void);
N_NOINLINE(void, HEX00_maybeInit)(void);
N_NOINLINE(void, HEX00_maybeDatInit)(void);
N_NOINLINE(void, testingInit)(void);
N_NOINLINE(void, testingDatInit)(void);
STRING_LITERAL(TMP136, "value", 5);
extern TFrame* frameptr_15242;
maybe90014 m1_90060;
maybe90014 m2_90067;
maybe90014 r_90201;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_15242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_15242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_15242;
	frameptr_15242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_17801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_15242 = (*frameptr_15242).prev;
}

N_NIMCALL(maybe90014, adder_90007)(NI x) {
	maybe90014 result;
	maybe90014 LOC1;
	NI TMP137;
	nimfr("adder", "testing.nim")
	memset((void*)&result, 0, sizeof(result));
	nimln(5, "testing.nim");
	nimln(5, "testing.nim");
	memset((void*)&LOC1, 0, sizeof(LOC1));
	LOC1.Valid = NIM_TRUE;
	if (!(((2 &(1<<((LOC1.Valid)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP136));
	nimln(5, "testing.nim");
	TMP137 = addInt(x, x);
	LOC1.validU.Value = (NI64)(TMP137);
	result = LOC1;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit();
	HEX00_monadDatInit();
	HEX00_maybeDatInit();
	testingDatInit();
	HEX00_monadInit();
	HEX00_maybeInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	testingInit();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_NOINLINE(void, testingInit)(void) {
	maybe90014 LOC1;
	maybe90014 LOC2;
	TY90098 LOC3;
	maybe90014 LOC4;
	TY90098 LOC5;
	maybe90014 LOC6;
	TY90098 LOC7;
	NimStringDesc* LOC8;
	nimfr("testing", "testing.nim")
	nimln(7, "testing.nim");
	memset((void*)&LOC1, 0, sizeof(LOC1));
	LOC1.Valid = NIM_TRUE;
	if (!(((2 &(1<<((LOC1.Valid)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP136));
	LOC1.validU.Value = 5;
	m1_90060 = LOC1;
	nimln(8, "testing.nim");
	memset((void*)&LOC2, 0, sizeof(LOC2));
	LOC2.Valid = NIM_FALSE;
	m2_90067 = LOC2;
	nimln(10, "testing.nim");
	nimln(10, "testing.nim");
	nimln(10, "testing.nim");
	memset((void*)&LOC3, 0, sizeof(LOC3));
	LOC3.ClPrc = ((TMP140) (adder_90007)); LOC3.ClEnv = NIM_NIL;
	LOC4 = HEX3EHEX3EHEX3D_90079(m1_90060, LOC3);
	memset((void*)&LOC5, 0, sizeof(LOC5));
	LOC5.ClPrc = ((TMP141) (adder_90007)); LOC5.ClEnv = NIM_NIL;
	LOC6 = HEX3EHEX3EHEX3D_90079(LOC4, LOC5);
	memset((void*)&LOC7, 0, sizeof(LOC7));
	LOC7.ClPrc = ((TMP142) (adder_90007)); LOC7.ClEnv = NIM_NIL;
	r_90201 = HEX3EHEX3EHEX3D_90079(LOC6, LOC7);
	nimln(11, "testing.nim");
	nimln(11, "testing.nim");
	LOC8 = 0;
	LOC8 = HEX24_90210(r_90201);
	printf("%s\012", (LOC8)->data);
	popFrame();
}

N_NOINLINE(void, testingDatInit)(void) {
}

