name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: brew install nim
    - name: Build
      run: nim c buildverify.nim
    - name: Test
      run: ./buildverify `which nim`
